config/routes.rb
Stm::Application.routes.draw do

  get "login"  => "sessions#new" , :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => 'signup'

  resources :users
  resources :sessions
  resources :stories do
    member do
      post 'start'
      post 'finish'
      post 'accept'
      post 'reject'
    end
    post 'filter', :on => :collection
  end
  resources :comments, :only => [:create, :destroy]
  
  root :to => "stories#index"

 end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :story
  validates :user_id, :story_id, :content, :presence => true
  
  state_machine :state, :initial => :new do
    
  end
  
end

app/models/story.rb
class Story < ActiveRecord::Base
  validates :title, :presence => true
  belongs_to :user
  has_many :comments

  state_machine :state, :initial => :new do

    event :start do
      transition :new => :started
    end
     
    event :finish do
      transition :started => :finished
    end
    
    event :accept do
      transition :finished => :accepted
    end
    
    event :reject do
      transition :finished => :rejected
    end
    
    event :restart do
      transition :rejected => :started
    end

  end
  
  def self.filter(user_id = nil, state = nil)
    if user_id.present? && state.present?
      where(:user_id => user_id, :state => state)
    elsif user_id.present?
      where(:user_id => user_id)
    elsif state.present?
      where(:state => state)
    else
      all
    end
  end
    
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation
  has_secure_password
  validates :email, :uniqueness => true
  has_many :stories
  has_many :comments
  
  scope :active, where(:state => "active")
  
  state_machine :state, :initial => :active do
    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def login_required
    unless current_user
      redirect_to login_url, :notice => "You must be logged in for this action"
    end
  end
  
  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :login_required
  
  def create
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    if @comment.save
      redirect_to story_path(@comment.story), :notice => 'Comment created'
    else
      @story = @comment.story
      @comments = @story.comments
      render 'stories/show'
    end
  end
  
  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to(story_path(@comment.story))
    end
  end
  

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, :notice => "Successfull login"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Successfull logout"
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :login_required, :except => :index

  def index
    @stories = Story.all
    @users = User.all
    @states = Story.state_machine.states.map{|s| s.name.to_s }
    
  end

  def filter
    @stories = Story.filter(params[:user_id], params[:state])
    @users = User.all
    @states = Story.state_machine.states.map{|s| s.name.to_s }
    render :action => 'index'
  end

  def new
    @story = Story.new
    @users = User.active
  end
  
  def create
    @story = Story.new(params[:story])
    if  @story.save
      redirect_to stories_url, :notice => "Story successfully created"
    else
      @users = User.active
      render "new"
    end
  end
  
  def edit
    @story = Story.find(params[:id])
    @users = User.active
  end
  
  def update
    @story = Story.find(params[:id])
    if @story.update_attributes(params[:story])
      redirect_to stories_url, :notice => "Story successfully updated"
    else
      @users = User.active
      render 'edit'
    end
  end
  
  def destroy
    @story = Story.find(params[:id])
    @story.destroy
    redirect_to stories_url, :notice => "Story successfully deleted"
  end
  
  def show
    @story = Story.find(params[:id])
    @comments = @story.comments
    @comment = @story.comments.new
  end
  
  def start
    @story = Story.find(params[:id])
    @story.start
    @story.user = current_user
    redirect_to stories_url
  end
  
  def finish
    @story = Story.find(params[:id])
    @story.finish
    redirect_to stories_url
  end
  
  def accept
    @story = Story.find(params[:id])
    @story.accept
    redirect_to stories_url
  end
  
  def reject
    @story = Story.find(params[:id])
    @story.reject
    redirect_to stories_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, :notice => 'Signed up!'
    else
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.haml
=form_for @comment, :html =>{:class => 'form-stacked'} do |f|
  -if @comment.errors.any?
    %div.errors_messages
    %h3=t(:processing_error)
    %ul
      -for mess in @comment.errors.full_messages
        %li=mess
  =f.label :content
  =f.text_area :content, {:class => 'span7', :rows => 3}
  %br/
  =f.hidden_field :story_id
  %br/
  =f.submit nil, {:class => 'btn'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Simple task manager
    = stylesheet_link_tag    "application"
    = stylesheet_link_tag "http://twitter.github.com/bootstrap/1.4.0/bootstrap.min.css"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body.container
  
    %div.flash
      - flash.each do |name, message|
        =content_tag :div, message, :id => "flash#{name}"
    %br/
    %div.user_nav
      -if current_user
        =t('user_nav.header')
        =current_user.email
        |
        =link_to t('user_nav.logout'), logout_path
      -else
        =link_to t('user_nav.signup'), signup_path
        |
        =link_to t('user_nav.login'), login_path

    =yield

app/views/stories/_filter.html.haml
%div
  = form_tag filter_stories_path do
    =t('filter.header')
    =t('filter.by_user')
    =select_tag :user_id, options_from_collection_for_select(@users, 'id', 'email', params[:user_id]), :include_blank => true
    =t('filter.by_state')
    =select_tag :state, options_for_select(@states, params[:state]), :include_blank => true
    =submit_tag t('filter.accept'), {:class => 'btn'}

app/views/stories/_form.html.haml
=form_for @story, :html =>{:class => 'form-stacked'} do |f|
  -if @story.errors.any?
    %div.errors_messages
    %h3=t(:processing_error)
    %ul
      -for mess in @story.errors.full_messages
        %li=mess

  =f.label :title
  %br/
  =f.text_field :title
  %br/
  =f.label :description
  %br/
  =f.text_area :description, {:class => 'span4', :rows => 5}
  %br/
  =f.label :user_id
  %br/
  =f.select :user_id, options_from_collection_for_select(@users, "id", "email"), :include_blank => true
  %br/
  %br/
  =f.submit nil, {:class => 'btn'}
  
=link_to t('story.back_link') , stories_path

app/views/stories/edit.html.haml
%h1=t('story.edit_header')

=render 'form'

app/views/stories/index.html.haml
%h1=t('story.stories')

-if @stories.present?
  %table.zebra-striped.bordered-table
    %thead
      %tr
        %th=t('story.title')
        %th=t('story.state')
        %th=t('story.user')
        %th
        %th
        %th
    -@stories.each do |story|
      %tr
        %td=story.title
        %td=story.state
        %td=story.user.try(:email)
        %td=link_to t(:show), story_path(story)
        %td=link_to t(:edit), edit_story_path(story)
        %td=link_to t(:delete), story, :method => 'delete'

-if current_user
  =render :partial => 'filter', :locals => {:users => @users, :states => @states}


%br/
=link_to t(:new), new_story_path

app/views/stories/new.html.haml
%h1=t('story.new')

=render 'form'

app/views/stories/show.html.haml
%h1="#{t('story.header')} : #{@story.title}"

%div.alert-message
  =t('story.description')
  %p
    =@story.description
  %br/
  -if @story.user
    User:
    =@story.user.try(:email)
  %br/
  -case @story.state
  -when "new"
    =button_to t('story.start'), start_story_path(@story), {:class => 'btn'}
  -when 'started'
    =button_to t('story.finish'), finish_story_path(@story), {:class => 'btn primary'}
  -when 'finished'
    =button_to t('story.accept'), accept_story_path(@story), {:class => 'btn success'}
    or
    =button_to t('story.reject'), reject_story_path(@story), {:class => 'btn danger'}

-if @comments.present?
  -@comments.all.each do |comment|
    %div.comment
      %b
        =comment.content
      %br/
      %br/
      =comment.user.email
      %div{:style => 'float:right'}
        =link_to t(:delete), comment, :method => 'delete'
        

%br/
%br/
%br/
=render :partial => 'comments/form'  
  
%br/
=link_to t('story.back_link'), stories_path

app/views/users/index.html.haml
%h1 Users

-if current_user
  =t('user_nav.header')
  =current_user.email

app/views/users/new.html.haml
%h1=t('user.signup')

= form_for @user, :html =>{:class => 'form-stacked'} do |f|
  -if @user.errors.any?
    %div.errors_messages
    %h3=t(:processing_error)
    %ul
      -for mess in @user.errors.full_messages
        %li=mess
            
  =f.label :email
  =f.text_field :email
  %br/
  =f.label :password
  =f.password_field :password
  %br/
  = f.label :password_confirmation
  =f.password_field :password_confirmation 
  %br/
  %br/
  = f.submit nil, {:class => "btn" }